import 'package:flutter/material.dart';
import 'cc_shared.dart';

// ── Transcript ────────────────────────────────────────────────────────────────

const _mockTranscript = [
  ('00:00', 'Tutor', "Good morning everyone, let's get started with today's session."),
  ('00:14', 'Tutor', 'We will be covering the key concepts from last week and building on them.'),
  ('01:02', 'Student', 'Can you repeat the formula from last class?'),
  ('01:10', 'Tutor', 'Of course. The formula is F = ma, where F is force, m is mass, and a is acceleration.'),
  ('02:30', 'Tutor', "Now let's apply this to a real-world problem. Imagine a car of 1000 kg accelerating at 2 m/s²."),
  ('03:45', 'Student', 'So the force would be 2000 N?'),
  ('03:50', 'Tutor', 'Exactly right! Great job.'),
  ('05:10', 'Tutor', "Let's move on to the next concept — Newton's third law."),
  ('06:20', 'Tutor', 'Newton\'s third law states: for every action there is an equal and opposite reaction.'),
  ('07:00', 'Student', 'Can you give an example?'),
  ('07:10', 'Tutor', 'Sure — when you push a wall, the wall pushes back on you with equal force.'),
];

class TranscriptSection extends StatelessWidget {
  const TranscriptSection({super.key});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final tt = Theme.of(context).textTheme;

    final content = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: _mockTranscript.map((entry) {
        final (time, speaker, text) = entry;
        final isTutor = speaker == 'Tutor';
        return Padding(
          padding: const EdgeInsets.only(bottom: 12),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                time,
                style: tt.labelSmall?.copyWith(
                  color: cs.onSurfaceVariant,
                  fontFeatures: const [FontFeature.tabularFigures()],
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      speaker,
                      style: tt.labelSmall?.copyWith(
                        color: isTutor ? cs.primary : cs.tertiary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(text, style: tt.bodySmall?.copyWith(color: cs.onSurface)),
                  ],
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );

    return CollapsibleSection(
      section: ClassSection.transcript,
      previewHeight: 220,
      child: content,
    );
  }
}

// ── AI Notes ──────────────────────────────────────────────────────────────────

const _mockAiNotes = [
  ('Key Concepts', [
    "Newton's Second Law: F = ma",
    'Force is measured in Newtons (N)',
    'Mass in kg, acceleration in m/s²',
  ]),
  ('Important Formulas', [
    'F = ma',
    'a = F / m',
    'Weight = mass × gravity (9.8 m/s²)',
  ]),
  ('Summary', [
    'Applied F = ma to a 1000 kg car at 2 m/s² → 2000 N',
    "Introduced Newton's Third Law for next session",
    'Student demonstrated understanding of force calculation',
  ]),
  ('Action Items', [
    'Practice problems 1–10 from Chapter 4',
    'Watch supplementary video on Newton\'s 3rd Law',
    'Prepare questions for next session',
  ]),
];

class AiNotesSection extends StatelessWidget {
  const AiNotesSection({super.key});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final tt = Theme.of(context).textTheme;

    final content = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: cs.primaryContainer.withValues(alpha: 0.4),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: cs.primaryContainer),
          ),
          child: Row(
            children: [
              Icon(Icons.auto_awesome_rounded, size: 16, color: cs.primary),
              const SizedBox(width: 8),
              Text(
                'Generated by Guru AI after class',
                style: tt.labelSmall?.copyWith(color: cs.primary, fontWeight: FontWeight.w600),
              ),
            ],
          ),
        ),
        const SizedBox(height: 12),
        ..._mockAiNotes.map((section) {
          final (heading, points) = section;
          return Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(heading, style: tt.titleSmall?.copyWith(color: cs.onSurface)),
                const SizedBox(height: 8),
                ...points.map((p) => Padding(
                      padding: const EdgeInsets.only(bottom: 6),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Container(
                            margin: const EdgeInsets.only(top: 6),
                            width: 5,
                            height: 5,
                            decoration: BoxDecoration(color: cs.primary, shape: BoxShape.circle),
                          ),
                          const SizedBox(width: 10),
                          Expanded(child: Text(p, style: tt.bodySmall?.copyWith(color: cs.onSurface))),
                        ],
                      ),
                    )),
              ],
            ),
          );
        }),
      ],
    );

    return CollapsibleSection(
      section: ClassSection.aiNotes,
      previewHeight: 220,
      child: content,
    );
  }
}
