import 'request_model.dart';

final mockRequests = [
  BookingRequest(
    id: '1',
    tutor: 'Vikram Singh',
    tutorImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    subject: 'IELTS',
    level: 'Band 7+',
    type: RequestType.demo,
    status: RequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 2)),
    preferredSlot: 'Mon 5:00 PM',
  ),
  BookingRequest(
    id: '2',
    tutor: 'Priya Sharma',
    tutorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    subject: 'Mathematics',
    level: 'JEE Advanced',
    type: RequestType.paid,
    status: RequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 5)),
    schedule: 'Mon, Wed, Fri - 5:00 PM',
    sessionsBooked: 100,
    perHourPrice: 499,
    classesPerWeek: 3,
    durationMonths: 8,
  ),
  BookingRequest(
    id: '3',
    tutor: 'Ananya Reddy',
    tutorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    subject: 'Chemistry',
    level: 'CBSE Grade 12',
    type: RequestType.paidDemo,
    status: RequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(days: 1)),
    preferredSlot: 'Tue 4:00 PM',
  ),
  BookingRequest(
    id: '4',
    tutor: 'Meera Patel',
    tutorImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    subject: 'Biology',
    level: 'NEET',
    type: RequestType.paid,
    status: RequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 3)),
    respondedAt: DateTime.now().subtract(const Duration(days: 2)),
    bookingAcceptedAt: DateTime.now().subtract(const Duration(hours: 2)),
    schedule: 'Tue, Thu, Sat - 6:00 PM',
    sessionsBooked: 80,
    perHourPrice: 599,
    classesPerWeek: 3,
    durationMonths: 6,
    isPaid: false,
  ),
  BookingRequest(
    id: '5',
    tutor: 'Rajesh Kumar',
    tutorImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    subject: 'Physics',
    level: 'JEE Mains',
    type: RequestType.paidDemo,
    status: RequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 2)),
    respondedAt: DateTime.now().subtract(const Duration(hours: 12)),
    bookingAcceptedAt: DateTime.now().subtract(const Duration(hours: 1)),
    preferredSlot: 'Mon 7:00 PM',
    isPaid: false,
  ),
  BookingRequest(
    id: '6',
    tutor: 'Sanjay Gupta',
    tutorImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    subject: 'English',
    level: 'TOEFL',
    type: RequestType.paid,
    status: RequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 5)),
    respondedAt: DateTime.now().subtract(const Duration(days: 4)),
    schedule: 'Tue, Thu - 8:00 PM',
    sessionsBooked: 40,
    perHourPrice: 399,
    classesPerWeek: 2,
    durationMonths: 5,
    isPaid: true,
  ),
  BookingRequest(
    id: '7',
    tutor: 'Kavya Iyer',
    tutorImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    subject: 'Mathematics',
    level: 'CBSE Grade 10',
    type: RequestType.demo,
    status: RequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 2)),
    respondedAt: DateTime.now().subtract(const Duration(days: 1)),
    preferredSlot: 'Wed 4:00 PM',
  ),
  BookingRequest(
    id: '10',
    tutor: 'Aisha Khan',
    tutorImage: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop',
    subject: 'Science',
    level: 'CBSE Grade 9',
    type: RequestType.paidDemo,
    status: RequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 6)),
    respondedAt: DateTime.now().subtract(const Duration(days: 5)),
    preferredSlot: 'Fri 3:00 PM',
    isPaid: true,
  ),
  BookingRequest(
    id: '8',
    tutor: 'Arjun Mehta',
    tutorImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    subject: 'Chemistry',
    level: 'JEE Advanced',
    type: RequestType.paid,
    status: RequestStatus.rejected,
    requestedAt: DateTime.now().subtract(const Duration(days: 4)),
    respondedAt: DateTime.now().subtract(const Duration(days: 3)),
    schedule: 'Mon, Wed, Fri - 6:00 PM',
    sessionsBooked: 50,
    rejectionReason: 'Schedule conflict',
  ),
  BookingRequest(
    id: '9',
    tutor: 'Neha Kapoor',
    tutorImage: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
    subject: 'Physics',
    level: 'NEET',
    type: RequestType.demo,
    status: RequestStatus.rejected,
    requestedAt: DateTime.now().subtract(const Duration(days: 5)),
    respondedAt: DateTime.now().subtract(const Duration(days: 4)),
    preferredSlot: 'Thu 5:00 PM',
    rejectionReason: 'Slot unavailable',
  ),
];
