import 'tutor_request_model.dart';

final mockTutorRequests = [
  TutorBookingRequest(
    id: '1',
    studentName: 'Aarav Kumar',
    studentImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop',
    subject: 'JEE Maths',
    level: 'JEE Advanced',
    type: TutorRequestType.paid,
    status: TutorRequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 1)),
    schedule: 'Mon, Wed, Fri - 5:00 PM',
    totalSessions: 100,
    perHourRate: 499,
    classesPerWeek: 3,
    totalPrice: 49900,
    inHandAmount: 37425,
    note: 'Need help with calculus and coordinate geometry. Preparing for JEE Advanced 2025.',
  ),
  TutorBookingRequest(
    id: '2',
    studentName: 'Diya Patel',
    studentImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    subject: 'Class 10 Physics',
    level: 'CBSE Grade 10',
    type: TutorRequestType.demo,
    status: TutorRequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 3)),
    preferredSlot: 'Tue 4:00 PM',
    note: 'Struggling with electricity and magnetism chapters.',
  ),
  TutorBookingRequest(
    id: '3',
    studentName: 'Rohan Sharma',
    studentImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    subject: 'NEET Biology',
    level: 'NEET',
    type: TutorRequestType.paid,
    status: TutorRequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 5)),
    schedule: 'Tue, Thu, Sat - 6:00 PM',
    totalSessions: 80,
    perHourRate: 599,
    classesPerWeek: 3,
    totalPrice: 47920,
    inHandAmount: 35940,
    note: 'Focus on genetics and human physiology.',
  ),
  TutorBookingRequest(
    id: '4',
    studentName: 'Ananya Singh',
    studentImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    subject: 'Class 12 Chemistry',
    level: 'CBSE Grade 12',
    type: TutorRequestType.demo,
    status: TutorRequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 8)),
    preferredSlot: 'Wed 5:00 PM',
    note: 'Need help with organic chemistry reactions.',
  ),
  TutorBookingRequest(
    id: '5',
    studentName: 'Arjun Reddy',
    studentImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    subject: 'JEE Physics',
    level: 'JEE Mains',
    type: TutorRequestType.paid,
    status: TutorRequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 1)),
    respondedAt: DateTime.now().subtract(const Duration(hours: 2)),
    schedule: 'Mon, Wed, Fri - 7:00 PM',
    totalSessions: 60,
    perHourRate: 549,
    classesPerWeek: 3,
    totalPrice: 32940,
    inHandAmount: 24705,
  ),
  TutorBookingRequest(
    id: '6',
    studentName: 'Priya Iyer',
    studentImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    subject: 'Class 9 Science',
    level: 'CBSE Grade 9',
    type: TutorRequestType.demo,
    status: TutorRequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 2)),
    respondedAt: DateTime.now().subtract(const Duration(days: 1)),
    preferredSlot: 'Thu 3:00 PM',
  ),
  TutorBookingRequest(
    id: '7',
    studentName: 'Kabir Mehta',
    studentImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    subject: 'NEET Chemistry',
    level: 'NEET',
    type: TutorRequestType.paid,
    status: TutorRequestStatus.declined,
    requestedAt: DateTime.now().subtract(const Duration(days: 3)),
    respondedAt: DateTime.now().subtract(const Duration(days: 2)),
    schedule: 'Tue, Thu - 8:00 PM',
    totalSessions: 50,
  ),
];

final mockRescheduleRequests = [
  TutorBookingRequest(
    id: 'r1',
    studentName: 'Aarav Kumar',
    studentImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop',
    subject: 'JEE Maths',
    level: 'JEE Advanced',
    type: TutorRequestType.reschedule,
    status: TutorRequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 2)),
    originalDate: DateTime.now().add(const Duration(days: 2)),
    originalTime: '5:00 PM',
    newDate: DateTime.now().add(const Duration(days: 3)),
    newTime: '6:00 PM',
    note: 'Have a school exam on the original date.',
  ),
  TutorBookingRequest(
    id: 'r2',
    studentName: 'Diya Patel',
    studentImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    subject: 'Class 10 Physics',
    level: 'CBSE Grade 10',
    type: TutorRequestType.reschedule,
    status: TutorRequestStatus.pending,
    requestedAt: DateTime.now().subtract(const Duration(hours: 6)),
    originalDate: DateTime.now().add(const Duration(days: 1)),
    originalTime: '4:00 PM',
    newDate: DateTime.now().add(const Duration(days: 1)),
    newTime: '7:00 PM',
    note: 'Family function in the evening.',
  ),
  TutorBookingRequest(
    id: 'r3',
    studentName: 'Rohan Sharma',
    studentImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    subject: 'NEET Biology',
    level: 'NEET',
    type: TutorRequestType.reschedule,
    status: TutorRequestStatus.accepted,
    requestedAt: DateTime.now().subtract(const Duration(days: 1)),
    respondedAt: DateTime.now().subtract(const Duration(hours: 3)),
    originalDate: DateTime.now().add(const Duration(days: 4)),
    originalTime: '6:00 PM',
    newDate: DateTime.now().add(const Duration(days: 5)),
    newTime: '5:00 PM',
  ),
];
